### ISSUE TITLE
Default react-native syntax use case.

### ISSUE THREAD

**Issue by michaltaberski** [johanneslumpe/react-native-gesture-recognizers#1]
on the Readme your example is using ES6 import mechanism, and ES7 decorators.

eg:

```
import React, { Component, Text, View } from 'react-native';
import { pannable } from 'react-native-gesture-recognizers';

@pannable({
  setGestureState: false
})
```

I assume you are using babel task, before you run the project.

How to make the gestures working with vanila ReactNative ES6?

**Comment by johanneslumpe** [comment]
Those are equivalent to this:

``` javascript
var { pannable } = require('react-native-gesture-recognizers');

class YourComponent {}
YourComponent = pannable({setGestureState: false})(YourComponent);
```

The destructuring assignment is enabled by default in the react-native babel configuration.

If you have any trouble getting this to work, feel free to post back here.

**Comment by RV2013** [comment]
This has worked for me and I ma sure will work for you as well. Please confirm whether this helped you or not.

 you can simply create a .babelrc file near index.ios.js and index.android.js that looks like:

{
  "plugins": [
    "transform-decorators"
  ]
}
