### ISSUE TITLE
Doesn't work in RN 0.39.2

### ISSUE THREAD

**Issue by sidevesh** [johanneslumpe/react-native-gesture-recognizers#13]
RN 0.39.2 uses babel 6, which seems to have issue with this, probably due to this using babel 5.  

`transformed 433/456 (95%)(node:12162) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 326): SyntaxError: TransformError: /home/sid/Developments/MyProjects/ProjectPrism/phone_app/PrismPhone/node_modules/react-native-gesture-recognizers/lib/index.js: [BABEL] /home/sid/Developments/MyProjects/ProjectPrism/phone_app/PrismPhone/node_modules/react-native-gesture-recognizers/lib/index.js: Using removed Babel 5 option: /home/sid/Developments/MyProjects/ProjectPrism/phone_app/PrismPhone/node_modules/react-native-gesture-recognizers/.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets`

**Comment by priyesh9875** [comment]
Did you got any workaround?. I am also facing same issue

**Comment by sidevesh** [comment]
didn't...sad i couldn't use this amazing library due to this issue

**Comment by johanneslumpe** [comment]
Updating this to Babel 6 shouldn't be a huge problem. I just don't have the time at the moment. The usage of decorators isn't required, as you could just call the function directly and pass in a component.

**Comment by sidevesh** [comment]
thanks...that would be great....will look into usage without decorators in meantime.

**Comment by priyesh9875** [comment]
@johanneslumpe Can you share the example project files which is there in the readme file plz.

**Comment by johanneslumpe** [comment]
@priyesh9875 There are no project files, those were just throw-away examples I used for screen capturing.

**Comment by sidevesh** [comment]
Trying to update it babel 6...when I clone the repo and run npm install i get this output:  
`
30227 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
30228 error node v6.9.2
30229 error npm  v4.1.1
30230 error code ELIFECYCLE
30231 error react-native-gesture-recognizers@0.2.3 prepublish: ``npm bin`/eslint src && rm -rf lib && `npm bin`/babel src --out-dir lib`
30231 error Exit status 1
30232 error Failed at the react-native-gesture-recognizers@0.2.3 prepublish script '`npm bin`/eslint src && rm -rf lib && `npm bin`/babel src --out-dir lib'.
30232 error Make sure you have the latest version of node.js and npm installed.
30232 error If you do, this is most likely a problem with the react-native-gesture-recognizers package,
30232 error not with npm itself.
30232 error Tell the author that this fails on your system:
30232 error     `npm bin`/eslint src && rm -rf lib && `npm bin`/babel src --out-dir lib
30232 error You can get information on how to open an issue for this project with:
30232 error     npm bugs react-native-gesture-recognizers
30232 error Or if that isn't available, you can get their info via:
30232 error     npm owner ls react-native-gesture-recognizers
30232 error There is likely additional logging output above.
30233 verbose exit [ 1, true ]
`  
  
Seems to be an issue with the command in prepublish script...  
also I found this https://github.com/johanneslumpe/react-native-gesture-recognizers/compare/master...radko93:master  
Any way to get this updated?

**Comment by AntoineGrandchamp** [comment]
As anyone found a way to use it without decorators ?

**Comment by MrHazimAli** [comment]
Any work around for this ? it appears transform error : Using removed babel 5 option.......

My RN version 0.42.0

**Comment by johanneslumpe** [comment]
This should be fixed with ed416620eaeb9f35a60d68d4b876b4f41f349d1f
