### ISSUE TITLE
Error: using removed babel 5 option

### ISSUE THREAD

**Issue by a-x-** [johanneslumpe/react-native-gesture-recognizers#14]
<details><summary>screen</summary>
<img src="https://cloud.githubusercontent.com/assets/6201068/24857342/9ed1be2a-1df0-11e7-80a1-ee38f9c29b31.png">
</details>

babel --version
6.14.0 (babel-core 6.14.0)

react-native --version
react-native-cli: 2.0.1
react-native: 0.43.2

xcode 8.3.1

macos 10.12.4

**Comment by tmaly1980** [comment]
me too!

**Comment by johanneslumpe** [comment]
This should be fixed with ed416620eaeb9f35a60d68d4b876b4f41f349d1f
