### ISSUE TITLE
Doesnt work with RN 0.17

### ISSUE THREAD

**Issue by mutp** [johanneslumpe/react-native-gesture-recognizers#4]
I get this error - 
<img width="379" alt="screenshot 2015-12-31 23 43 34" src="https://cloud.githubusercontent.com/assets/8210008/12067016/55fcb39a-b018-11e5-9a8e-e65ac10fa099.png">

**Comment by mutp** [comment]
Was working with RN 0.13, this error comes up with RN 0.17

**Comment by johanneslumpe** [comment]
@adarshmuthappa This is most likely due to the fact that RN updated to Babel 6. This project still uses options for Babel 5 and thus is not compatible as of now.

**Comment by kwcto** [comment]
Try deleting the .babelrc.stage

**Comment by cherniv** [comment]
@kwcto doesn't help, error still exists

**Comment by faceyspacey** [comment]
it doesnt work for 0.22.0 either. this is a great project, but it seems the use of decorators is blocking it from being used. Maybe I'm just not in the know--how do enable this project for 0.22.0? How do I enable decorators? ...gonna look it up, but would be nice if an explanation on decorators was provided for those not using it, which likely is the majority--I haven't seen decorators used in any other react native package example (and I've looked at almost all of them).

**Comment by faceyspacey** [comment]
ok, i get the decorator stuff. doing that manually in a way that looks like connecting in redux works, but i'm still getting the babel issues. It seems I'm supposed to do something like this:

http://stackoverflow.com/questions/34301739/run-a-custom-babel-transform-with-react-native/34311400#34311400

we should document exactly how this is done here. When I figure it out I'll make a PR on the readme.

**Comment by johanneslumpe** [comment]
This should be fixed with ed416620eaeb9f35a60d68d4b876b4f41f349d1f
